<?php
/**
 * @file
 * Ding - toggle short/long format
 */


/**
 * Implements hook_block_info().
 */
function ding_toggle_format_block_info() {
  return array(
    'toggle' => array(
      'info' => t('Ding format toggle'),
      'cache' => DRUPAL_CACHE_PER_PAGE,
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function ding_toggle_format_block_view($delta = '') {

  drupal_add_js(drupal_get_path('module', 'ding_toggle_format') . '/js/ding_toggle_format.js');
  drupal_add_js(drupal_get_path('module', 'ding_toggle_format') . '/js/jquery.cookie.min.js');

  drupal_add_css(drupal_get_path('module', 'ding_toggle_format') . '/css/ding_toggle_format.css');

  return array(
    'subject' => t('Ding toggle format'),
    'content' => ding_toggle_format_render_link(),
  );
}

/**
 * Return rendered image link to toggle format, and label.
 */
function ding_toggle_format_render_link() {
  // get view_type from url
  $view_type = arg(1);

  $markup = NULL;

  // render image html using theme_image (returns NULL if file doesn't exist)
  if ($view_type != 'collection') {
    $markup = array(
      array(
        '#markup' => '<div class="btn-toolbar" id="ding-toggle-format"><div class="btn-group">',
      ),
      array(
        '#theme' => 'link',
        '#text' => '<i class="icon-white icon-list"></i>',
        '#path' => current_path(),
        '#options' => array(
          'attributes' => array(
            'class' => array(
              'ding-toggle-format-long',
              'btn',
              'btn-artesis-turquoise',
            ),
            'title'=> t('Toggle format: long'),
          ),
          'html' => TRUE,
        ),
      ),
      array(
        '#theme' => 'link',
        '#text' => '<i class="icon-white icon-th"></i>',
        '#path' => current_path(),
        '#options' => array(
          'attributes' => array(
            'class' => array(
              'ding-toggle-format-short',
              'btn',
              'btn-artesis-turquoise',
            ),
            'title'=> t('Toggle format: short'),
          ),
          'html' => TRUE,
        ),
      ),
      array(
        '#markup' => '</div></div>',
      ),
    );
  }

  return $markup;
}

